// Generated by Ludicord. Changes will be replaced by ludicord dev or ludicord build.
import "ludicord/navigation";

declare module "ludicord/navigation" {
  interface LudicordRouteRegistry {
    readonly embed: "home" | "me" | "xo";
    readonly embedPattern: "home" | "me" | "xo";
    readonly api: never;
    readonly websocket: "/ws/hide" | "/ws/hockey" | "/ws/xo";
    readonly embedParams: {
      readonly "home": Readonly<Record<string, never>>;
      readonly "me": Readonly<Record<string, never>>;
      readonly "xo": Readonly<Record<string, never>>;
    };
    readonly config: {
      readonly defaultEmbed: "home";
      readonly outsideDiscord: "allow";
      readonly authRequired: true;
    };
  }
}
